import { FC } from "react";
import Head from "next/head";
import Carousel from "react-multi-carousel";
import { MdKeyboardArrowDown, MdKeyboardArrowUp } from "react-icons/md";
import BlockVideo from "components/shared/Blocks/Video/Video";
import BlockSlider from "components/shared/Blocks/Slider/Slider";

interface ViewHomeProps {
    data: any;
}

const ViewHome: FC<ViewHomeProps> = ({ data }) => {
    return (
        <div className="block">
            <Head>
                <title>Slide</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Carousel
                    additionalTransfrom={0}
                    showDots
                    arrows
                    autoPlaySpeed={3000}
                    centerMode={false}
                    focusOnSelect={false}
                    keyBoardControl
                    minimumTouchDrag={80}
                    pauseOnHover
                    renderArrowsWhenDisabled={false}
                    renderButtonGroupOutside={false}
                    renderDotsOutside
                    rewind={false}
                    rewindWithAnimation={false}
                    rtl={false}
                    shouldResetAutoplay
                    slidesToSlide={1}
                    swipeable={false}
                    draggable={false}
                    customDot={<CustomDot />}
                    customRightArrow={<CustomRightArrow />}
                    customLeftArrow={<CustomLeftArrow />}
                    responsive={{
                        superLargeDesktop: {
                            breakpoint: { min: 1920, max: 4000 },
                            items: 1,
                        },
                        desktop: {
                            breakpoint: { min: 1024, max: 1920 },
                            items: 1,
                        },
                        tablet: {
                            breakpoint: { min: 640, max: 1024 },
                            items: 1,
                        },
                        mobile: {
                            breakpoint: { max: 640, min: 0 },
                            items: 1,
                            slidesToSlide: 1,
                        },
                    }}
                >
                    {data.data.map((item: any, index: number) => {
                        switch (item.typename) {
                            case "BlockVideo":
                                return <BlockVideo key={index} item={item} />;

                            case "BlockSlider":
                                return <BlockSlider key={index} item={item} />;
                        }
                    })}
                </Carousel>
            </main>
        </div>
    );
};

const CustomDot = ({ onClick, ...rest }: any) => {
    const { active } = rest;

    return <button className={active ? "react-multi-carousel-custom-dot--active" : "react-multi-carousel-custom-dot--inactive"} onClick={() => onClick()} />;
};

const CustomRightArrow = ({ onClick }: any) => {
    return (
        <button className="react-multi-carousel-arrow" onClick={() => onClick()}>
            <MdKeyboardArrowDown />
        </button>
    );
};

const CustomLeftArrow = ({ onClick }: any) => {
    return (
        <button className="react-multi-carousel-arrow" onClick={() => onClick()}>
            <MdKeyboardArrowUp />
        </button>
    );
};

export default ViewHome;
